import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import ReduxProvider from "./redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Sidebar />
        <ReduxProvider>{children}</ReduxProvider>
        </body>
    </html>
  );
}
//verificar si estan permitidos los scripts
//Get-ExecutionPolicy

//habilitar scripts en windows, en powershild
//Set-ExecutionPolicy Unrestricted  